// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ3hrJj3I4_q49kceDTYWVGVOafcBxSAw',
    appId: '1:924395100608:web:5a15bc47962da38d359025',
    messagingSenderId: '924395100608',
    projectId: 'koyo-b6f9f',
    authDomain: 'koyo-b6f9f.firebaseapp.com',
    storageBucket: 'koyo-b6f9f.appspot.com',
    measurementId: 'G-PCD9X11FSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzhSApTLOYel7bS3n1UocqmilnvuTApkY',
    appId: '1:924395100608:android:356f5cd306c2a7d2359025',
    messagingSenderId: '924395100608',
    projectId: 'koyo-b6f9f',
    storageBucket: 'koyo-b6f9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEJ9SQhYpzi6aaaJT63Y8abbbS4Pt-bzo',
    appId: '1:924395100608:ios:72dc48ae55125eaf359025',
    messagingSenderId: '924395100608',
    projectId: 'koyo-b6f9f',
    storageBucket: 'koyo-b6f9f.appspot.com',
    iosBundleId: 'com.example.koyo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEJ9SQhYpzi6aaaJT63Y8abbbS4Pt-bzo',
    appId: '1:924395100608:ios:686edc07df1e7596359025',
    messagingSenderId: '924395100608',
    projectId: 'koyo-b6f9f',
    storageBucket: 'koyo-b6f9f.appspot.com',
    iosBundleId: 'com.example.koyo.RunnerTests',
  );
}
